# 通用连接池配置
# 注意：实际产生的数据库连接数为 (Celery workers 数量 * max_size)
# 线程数并不会直接创建达到 max_size 的数量，而是根据线程需要增长
thrift:
  max_size: 3       # 最大连接数，0 不限
  max_usage: 100000 # 可使用次数，0 不限
  idle: 60          # 连接可闲置时间(秒)，0 不限
  ttl: 3600         # 连接可使用时间(秒)，0 不限
  block: true       # 连接池满时，是否阻塞等待空闲连接

